/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export enum EvidenceArtifactType {
    ITEM_PHOTO = 'ITEM_PHOTO',
    CONDITION_PHOTO = 'CONDITION_PHOTO',
    IDENTIFIER_PHOTO = 'IDENTIFIER_PHOTO',
    COA_PHOTO = 'COA_PHOTO',
    PACKING_VIDEO = 'PACKING_VIDEO',
    SHIPPING_LABEL = 'SHIPPING_LABEL',
    UNBOXING_VIDEO = 'UNBOXING_VIDEO',
    DELIVERY_PHOTO = 'DELIVERY_PHOTO',
    SUPPORTING_DOCUMENT = 'SUPPORTING_DOCUMENT',
    RETURN_CONDITION_PHOTO = 'RETURN_CONDITION_PHOTO',
    RETURN_PACKING_VIDEO = 'RETURN_PACKING_VIDEO',
    RETURN_SHIPPING_LABEL = 'RETURN_SHIPPING_LABEL',
    RETURN_UNBOXING_VIDEO = 'RETURN_UNBOXING_VIDEO',
    PHYSICAL_REFERENCE_FRAME = 'PHYSICAL_REFERENCE_FRAME',
    PHYSICAL_VERIFICATION_FRAME = 'PHYSICAL_VERIFICATION_FRAME',
}
